title: 樊融
description: My Personal Blog
author: 樊融
logo: static/img/avatar.png
github: https://github.com/fairyrong
about: 爱笑 爱生活 爱学习 の前端girl

baseurl: ""
url: "http://fairyrong.github.io"

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
